"""Add ts_vector field

Revision ID: 15a6ad4fe0a7
Revises: e91cf67ca687
Create Date: 2020-05-19 01:30:35.883351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "15a6ad4fe0a7"
down_revision = "1e45fde8fa8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lection", sa.Column("tsvector_ru", postgresql.TSVECTOR(), nullable=True)
    )
    op.create_index(
        "idx_gin_tsvector_ru",
        "lection",
        ["tsvector_ru"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_gin_tsvector_ru", table_name="lection")
    op.drop_column("lection", "tsvector_ru")
    # ### end Alembic commands ###
