"""initial tables

Revision ID: 1e45fde8fa8e
Revises: d4867f3a4c0a
Create Date: 2020-05-18 21:31:54.894387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e45fde8fa8e"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_country_id"), "country", ["id"], unique=False)
    op.create_table(
        "lection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("content_ru", sa.String(), nullable=True),
        sa.Column("content_en", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("is_public_program", sa.Boolean(), nullable=False),
        sa.Column("has_video", sa.Boolean(), nullable=False),
        sa.Column("has_audio", sa.Boolean(), nullable=False),
        sa.Column("is_unknown_source", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["country_id"], ["country.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lection_id"), "lection", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lection_id"), table_name="lection")
    op.drop_table("lection")
    op.drop_index(op.f("ix_country_id"), table_name="country")
    op.drop_table("country")
    # ### end Alembic commands ###
