default_context:
  project_name: 'sahajalib'
  project_slug: 'sahajalib'
  domain_main: 'sahajalib.com'
  domain_staging: 'stag.sahajalib.com'
  docker_swarm_stack_name_main: 'sahajalib-com'
  docker_swarm_stack_name_staging: 'stag-sahajalib-com'
  secret_key: '347c2672ee35b34e85d8dcba75c7cfc61c982842198ce91e13be4738fd09f6e5'
  first_superuser: 'admin@sahajalib.com'
  first_superuser_password: ',3ccv3hn13'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.sahajalib.com, https://stag.sahajalib.com, https://sahajalib.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@sahajalib.com'
  postgres_password: '9a59b861e101e2c372d2'
  pgadmin_default_user: 'admin@sahajalib.com'
  pgadmin_default_user_password: ',3ccv3hn13'
  traefik_constraint_tag: 'sahajalib.com'
  traefik_constraint_tag_staging: 'stag.sahajalib.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:,3ccv3hn13'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
