version: '3'
services:

  postgres:
    restart: on-failure
    build:
      context: ./database
      dockerfile: postgres.dockerfile
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./database/pg_data:/var/lib/postgresql/data
    env_file:
      - .env.docker

  api-backend:
    build:
      context: ./api-backend
    command: sh -c "python manage.py migrate --no-input --fake-initial && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.docker
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./api-backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
      args:
          FRONTEND_ENV: production
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./certbot/www:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
