version: '3'
services:

  postgres:
    restart: on-failure
    build:
      context: ./database
      dockerfile: postgres.dockerfile
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./database/pg_data:/var/lib/postgresql/data
    env_file:
      - api-backend/.env.local
