# Generated by Django 4.0.2 on 2022-08-02 18:09

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="Lection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("content_ru", models.TextField(blank=True, null=True)),
                ("content_en", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("is_public_program", models.BooleanField()),
                ("has_video", models.BooleanField()),
                ("has_audio", models.BooleanField()),
                ("is_unknown_source", models.BooleanField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tsvector_ru",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.country",
                    ),
                ),
            ],
            options={
                "db_table": "lection",
            },
        ),
    ]
