# Generated by Django 4.0.2 on 2024-09-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lection_is_lection_lection_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='is_meta',
            field=models.BooleanField(default=False),
        ),
    ]
