name: CI/CD

on:
  push:
    branches: [ main, ci, feature/nginx-ssl ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Navigate to the project directory
          cd sahaja-library
          
          echo ${GITHUB_SHA}
          echo ${{github.sha}}
          
          # Reset to the commit that triggered the workflow
          git fetch origin
          git reset --hard ${{github.sha}}

          pwd

          # Build and start the services
          docker compose build
          docker compose up -d

          # Optional: Run database migrations
          # docker compose exec -T api-backend python manage.py migrate

          # Optional: Load fixtures if needed
          # docker compose exec -T api-backend python manage.py loaddata fixtures.json

          # Clean up old images
          # docker image prune -f
